name: Continous Deployment
on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
jobs:
    build:
        runs-on: windows-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2.3.5

            - name: Set-up Node
              uses: actions/setup-node@v2.4.1
              with:
                  node-version: "16"

            - name: Install and build
              run: |
                npm install 
                npm run build

            - name: Upload Artifact
              uses: actions/upload-artifact@v1
              with: 
                name: site
                path: dist
    deploy:
        needs: [build]
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2.3.5
            
            - name: Download Artifacts
              uses: actions/download-artifact@v1
              with: 
                name: site

            - name: deploy
              if: ${{ github.event_name == 'push' }}
              uses: JamesIves/github-pages-deploy-action@4.1.5
              with:
                branch: gh-pages
                folder: site
